### ISSUE TITLE
Marine sedimenter - tegneregler

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#682]
**Is your feature request related to a problem? Please describe.**
NGU jobber med oversettelse av marine bunnsedimneter til NiN (bl. a. S3E, S1 m.fl) Ønsker implementering av tegneregler fra SOSI

**Describe the solution you'd like**
Eksisterende tegneregler for marine sediment ligger her : http://www.ngu.no/upload/Kartkatalog/Presentasjonsregler_Marin_SedimentKornstorrelseDet.pdf

Tror vi forøker en myk implementing Farkekoder men ikke skravur)

**Describe alternatives you've considered**
Skavur vil gi store utfordringer mht frafisk "AND" funksjonalitet.

**Additional context**
Datasettet foreligger ikke enda. Issue oppdateres når aktuelt!

**Comment by bjornreppen** [comment]
Proprietære .lyr-filer lenket fra .pdfen over: http://www.ngu.no/upload/Kartkatalog/lyr/ 

Vært fint om noen med ESRI software kunne eksportert .lyr-fila til for eksempel QGIS .qlr
https://gis.stackexchange.com/questions/24300/adding-layerfiles-lyr-to-qgis

**Comment by bjornreppen** [comment]
Maybe try this conversion program: https://github.com/nyalldawson/slyr

**Comment by runningbones** [comment]
[Tabell oversetter SOSI_NiN2_sept2018_AAVE.xlsx](https://github.com/Artsdatabanken/ratatouille/files/2694995/Tabell.oversetter.SOSI_NiN2_sept2018_AAVE.xlsx)

**Comment by runningbones** [comment]
SOSI_navn, 

AKtuelle kolonner: SOSI_navn | NiN2_S3E |  NiN2_S3F |

**Comment by bjornreppen** [comment]
SLYR can not be used: "Currently only ESRI .style database files are supported. There's similarities between .style blobs and .lyr files, but more work is required in order to directly support .lyr file conversion. In the meantime, it is necessary to use ArcGIS to convert a .lyr file to a .style database prior to conversion with SLYR."  https://github.com/nyalldawson/slyr

Doing it manually.  Thanks ESRI for making file formats public and open. :-(

**Comment by bjornreppen** [comment]
Fargene var kanskje et litt vanskelig utgangspunkt for bruk i S3E?   Vises blandet i XYZ (over) og RGB (under) fargemodell.

![image](https://user-images.githubusercontent.com/281359/50281197-fb349c00-044e-11e9-9a7b-6bc39129e4a2.png)
